[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pixel-counter"
version = "0.1.0"
description = "Pokemon bead color counter"
readme = "README.md"
requires-python = ">=3.12"

[project.scripts]
pixel-counter = "pixel_counter.cli:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
